# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{outside-in}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brian Moseley"]
  s.date = %q{2010-09-20}
  s.email = %q{brian@outside.in}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "HISTORY",
     "README.md",
     "Rakefile",
     "VERSION",
     "config/oi.sample.yml",
     "config/oi.yml",
     "doc/OI.html",
     "doc/OI/ApiException.html",
     "doc/OI/Base.html",
     "doc/OI/Category.html",
     "doc/OI/ForbiddenException.html",
     "doc/OI/HttpException.html",
     "doc/OI/Location.html",
     "doc/OI/NotFoundException.html",
     "doc/OI/QueryException.html",
     "doc/OI/QueryParams.html",
     "doc/OI/Resource.html",
     "doc/OI/Resource/Base.html",
     "doc/OI/Resource/LocationFinder.html",
     "doc/OI/Resource/StoryFinder.html",
     "doc/OI/ServiceException.html",
     "doc/OI/SignatureException.html",
     "doc/OI/Story.html",
     "doc/OI/Tag.html",
     "doc/_index.html",
     "doc/class_list.html",
     "doc/css/common.css",
     "doc/css/full_list.css",
     "doc/css/style.css",
     "doc/file.README.html",
     "doc/file_list.html",
     "doc/frames.html",
     "doc/index.html",
     "doc/js/app.js",
     "doc/js/full_list.js",
     "doc/js/jquery.js",
     "doc/method_list.html",
     "doc/top-level-namespace.html",
     "lib/oi.rb",
     "lib/oi/base.rb",
     "lib/oi/category.rb",
     "lib/oi/location.rb",
     "lib/oi/query_params.rb",
     "lib/oi/resource/base.rb",
     "lib/oi/resource/location_finder.rb",
     "lib/oi/resource/story_finder.rb",
     "lib/oi/story.rb",
     "lib/oi/tag.rb",
     "outside-in.gemspec",
     "tasks/oi.thor"
  ]
  s.homepage = %q{http://github.com/outsidein/api-rb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ruby SDK for the Outside.in API}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

